spring:
  datasource:
    username: root
    password: ****
    url: jdbc:mysql://47.103.29.1:3306/mesrobot
    driver-class-name: com.mysql.cj.jdbc.Driver
    data:
      solr:
        host: http://47.103.29.1:8080/solr/mesrobot
  application:
    name: solr-eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8081